const problems =  [
    "Write a program to print 'Hello, World!'",
    "Write a program to input two numbers and display their sum.",
    "Write a program to input three numbers and find the largest among them.",
    "Write a program to swap two numbers using a temporary variable.",
    "Write a program to calculate the area of a circle given its radius.",
    "Write a program to convert temperature from Celsius to Fahrenheit.",
    "Write a program to find the ASCII value of a character.",
    "Write a program to check if a number is even or odd.",
    "Write a program to find the factorial of a number.",
    "Write a program to print numbers from 1 to 10 using a loop.",
    "Write a program to calculate the sum of the first N natural numbers.",
    "Write a program to determine if a year is a leap year or not.",
    "Write a program to reverse a number using a loop.",
    "Write a program to input 5 integers and display them.",
    "Write a program to find the largest number in an array.",
    "Write a program to find the smallest number in an array.",
    "Write a program to calculate the sum of elements in an array.",
    "Write a program to find the average of numbers in an array.",
    "Write a program to count the number of even and odd elements in an array.",
    "Write a program to input and display a string.",
    "Write a program to find the length of a string (without using a library function).",
    "Write a program to reverse a string.",
    "Write a program to check if a string is a palindrome.",
    "Write a program to concatenate two strings (without using a library function).",
    "Write a function to calculate the square of a number.",
    "Write a function to find the factorial of a number.",
    "Write a program to find the sum of two numbers using a function.",
    "Write a program to demonstrate the use of pointers.",
    "Write a program to swap two numbers using pointers.",
    "Write a program to find the sum of elements in an array using pointers.",
    "Write a program to create and write to a file.",
    "Write a program to read the content of a file and display it on the screen.",
    "Write a program to calculate the sum of the digits of a number.",
    "Write a program to find if a number is prime or not.",
    "Write a program to generate the Fibonacci series up to N terms.",
    "Write a program to find the greatest common divisor (GCD) of two numbers.",
    "Write a program to find the least common multiple (LCM) of two numbers.",
    "Write a program to calculate the power of a number (a^b).",
    "Write a program to count the number of vowels in a string.",
    "Write a program to find the sum of diagonal elements of a 2D matrix.",
    "Write a program to print all prime numbers between 1 and 100.",
    "Write a program to find the sum of all prime numbers between two numbers.",
    "Write a program to generate Pascal's triangle.",
    "Write a program to print the pattern:\n*\n**\n***\n****\n*****",
    "Write a program to sort an array in ascending order.",
    "Write a program to sort an array in descending order.",
    "Write a program to merge two arrays.",
    "Write a program to find the second largest element in an array.",
    "Write a program to rotate an array to the left by one position.",
    "Write a program to find the frequency of each element in an array.",
    "Write a program to check if two strings are anagrams.",
    "Write a program to find the first non-repeating character in a string.",
    "Write a program to find the number of words in a string.",
    "Write a program to remove all vowels from a string.",
    "Write a program to count the occurrences of a character in a string.",
    "Write a recursive function to calculate the GCD of two numbers.",
    "Write a recursive function to calculate the power of a number (a^b).",
    "Write a function to find the maximum and minimum elements in an array.",
    "Write a program to find the length of a string using pointers.",
    "Write a program to reverse an array using pointers.",
    "Write a program to find the largest number in an array using pointers.",
    "Define a structure to store student details and display them.",
    "Write a program to calculate the total marks of students using structures.",
    "Write a program to store employee details and sort them by salary.",
    "Write a program to store and display details of books using structures.",
    "Write a program to count the number of lines in a file.",
    "Write a program to append content to an existing file.",
    "Write a program to copy the content of one file to another.",
    "Write a program to allocate memory for an array dynamically and calculate its sum.",
    "Write a program to reallocate memory for an array dynamically.",
    "Write a program to free dynamically allocated memory.",
    "Write a program to add two matrices.",
    "Write a program to multiply two matrices.",
    "Write a program to find the transpose of a matrix.",
    "Write a program to check if a matrix is symmetric or not.",
    "Write a program to count the number of set bits in a number.",
    "Write a program to check if a number is a power of 2.",
    "Write a program to swap two numbers using bitwise XOR.",
    "Write a program to implement a simple calculator using switch-case.",
    "Write a program to implement binary search.",
    "Write a program to implement linear search.",
    "Write a program to implement bubble sort.",
    "Write a program to implement insertion sort.",
    "Write a program to implement selection sort.",
    "Write a program to find the determinant of a 2x2 matrix.",
    "Write a program to check if a number is an Armstrong number.",
    "Write a program to check if a number is a perfect number.",
    "Write a program to convert a binary number to decimal.",
    "Write a program to convert a decimal number to binary.",
    "Write a program to implement a stack using arrays.",
    "Write a program to implement a queue using arrays.",
    "Write a program to check if a number is palindrome.",
    "Write a program to find the sum of cubes of digits of a number.",
    "Write a program to implement a priority queue using structures.",
    "Write a program to generate a magic square of size N.",
    "Write a program to solve the Tower of Hanoi problem.",
    "Write a program to implement a singly linked list.",
    "Write a program to implement a doubly linked list.",
    "Write a program to find the intersection of two arrays.",
    "Write a program to generate combinations of a given string."
  ]





module.exports = problems;